### ISSUE TITLE
PollExisting only work once

### ISSUE THREAD

**Issue by notes2c** [g0t4/Rx-FileSystemWatcher#1]
The first time you make a PollExisting it is working okay. But if you try to perform at a second PollExisting on the same instance nothing is happining. It is at as the subscription is lost after first PollExisting.

**Comment by g0t4** [comment]
Can you reproduce this with a test?

**Comment by notes2c** [comment]
At first I will say that I am quite new to Rx but I am trying to do this


        private BindingList<FileDropped> dataContext;

        [Test]
        public void PollExistingTwice()
        {
            dataContext = new BindingList<FileDropped>();           
            using (var watcher = new FileDropWatcher(TempPath, "Monitored.Txt"))
            {
                watcher.Dropped.Subscribe(OnReceiveFileDropped); 
                var monitoredFile = Path.Combine(TempPath, "Monitored.Txt");
                File.WriteAllText(monitoredFile, "foo");

                watcher.PollExisting();

                Assert.IsTrue(dataContext.Count > 0);

                dataContext.Clear();

                Assert.IsTrue(dataContext.Count == 0);
                
                watcher.PollExisting();

                Assert.IsTrue(dataContext.Count > 0);
            }
        }

        private void OnReceiveFileDropped(FileDropped item)
        {
            dataContext.Add(item);
        }

**Comment by g0t4** [comment]
Fixed in adc91c60723a0b47d094eb783e5c1f5a8e63801d

**Comment by g0t4** [comment]
https://www.nuget.org/packages/ReactiveFileSystemWatcher/0.1.2.1
